title: Trident Fox
description: "Software that moves with your ambition"
url: "https://abdullahharithworks.github.io"
baseurl: ""

markdown: kramdown

# Company-specific variables
company_name: "Trident Fox"
company_tagline: "We craft software that adapts, scales, and propels your ideas into motion."
company_email: "hello@tridentfox.com"
company_github: "https://github.com/tridentfox"
company_linkedin: "https://linkedin.com/company/tridentfox"
