title: Amber Rook
description: "Software that moves with your ambition"
url: "https://abdullahharithworks.github.io"
baseurl: ""

markdown: kramdown

# Company-specific variables
company_name: "Amber Rook"
company_tagline: "We craft software that adapts, scales, and propels your ideas into motion."
company_email: "hello@amberrook.com"
company_github: "https://github.com/amberrook"
company_linkedin: "https://linkedin.com/company/amberrook"
